### ISSUE TITLE
Add Homebrew formula

### ISSUE THREAD

**Issue by martinswanson** [javacc/javacc#100]
I noticed there is no existing Homebrew formula for JavaCC. It would be very nice (especially for new community members) to create one to standardize installation and environment config for macOS. 

I have created a formula locally and tested it. The formula is working but I had to modify the build.xml file (to specify the Main.Class tag in the MANIFEST.MF file) and rebuild the jar locally to get it to work.

Without updating the build.xml it won't be possible to commit the formula to the Homebrew repository.

Questions:
- Has anyone else got Homebrew working for JavaCC?
- Are there any concerns with modifying the build.xml file? 
- Is it sufficient to specify the org.javacc.parser.Main class, or do we need the ability to call other Main classes packaged the jar?

Thanks,
Martin

**Comment by zosrothko** [comment]
Hi @martinswanson You can psuh any PR that improves JavaCC. There is few or no concern in modifying build.xml as soon as it continue to work for other platforms. The real concerns are related to the JavaCC language itself.

**Comment by martinswanson** [comment]
This can be closed, javacc formula for homebrew exists and supports latest 7.0.5 build.
https://formulae.brew.sh/formula/javacc
