### ISSUE TITLE
How to get the complete parsed text?

### ISSUE THREAD

**Issue by AngledLuffa** [javacc/javacc#121]
I've been working on a tool for Stanford NLP which incorporates javacc for building one of its utilities, semgrex (short for semantic graph expressions).  There's a confusing part of the syntax which some people have misinterpreted, so I have added new functionality with much clearer semantics which does the same thing.  As part of this change, I would like to deprecate the old, unclear version of the expressions.

Part of this would be to report when the old version has been used.  Something like log.warn("This particular syntax has been deprecated.  You can replace " + XYZ + " with the following expression: " + (new expression)");

What takes the place of XYZ?  This can be called as part of the final (or from the POV of the stack, the initial) method call, so the entire expression will have been processed at the time of printing the warning.

Thanks!

**Comment by MarcMazas** [comment]
Hi

It looks that XYZ will be the list of tokens matched by the old expression.
You will need to reach the end of the old expression to have it.
void Expr() : Old_expr() {warn("bla" + the_oe_str);} | New_expr()

See the JavaCC API for parser actions and the Token class.

Depending on its syntax and complexity, you can build this list string in different ways:
- concatenate the token.image(s) in a global variable (like the_oe_str above)
- concatenate the token.image(s) making your productions return them (String Old_exp_sub_exp())
- record the first token in a global variable and when encountering the last one traverse the tokens list from the first one to the last one through token.next
- ...

In all cases take care if your syntax can be recursive, if yes handle accordingly global variables with saves / restores.

Hope this helps.

**Comment by AngledLuffa** [comment]
This does help, thanks!  I am outputting the message at the end of the root production, so I guess it doesn't even need to be a global variable for tracking the first token, just a local variable.  Have added that for the next release.
