### ISSUE TITLE
DFA behaves differently on v.8.0.0

### ISSUE THREAD

**Issue by mbrigl** [javacc/javacc#130]
Using following test-grammar and applying the tokenizer on "NS.Attr IS .56"; version 7 and version 8 return different results. The result of version 7 is the expected:

- Version 7: "ATTR_TOKEN" "DOT" "ATTR_TOKEN" "EQUALS" "DECIMAL_TOKEN"
                   NS . Attr eq .56 
- Version 8: "ATTR_TOKEN" "DOT" "ATTR_TOKEN" "EQUALS" "DOT" "DECIMAL_TOKEN"
                   NS .  Attr eq . 56 

~~~
SKIP :
{
  "\u0020"	/* Space */
}

TOKEN:
{
  < DOT : "." >
| < INTEGER_TOKEN : "0" | [ "1"-"9" ] (< DIGIT >) * >
| < DECIMAL_TOKEN : "NaN" | "Infinity" | < DECIMAL > | < INTEGER_TOKEN > >

| < #DIGIT :	["0"-"9"] >
| < #DECIMAL :	("0" | ["1"-"9"] (< DIGIT >) * ) ? "." (< DIGIT >)+ >
}


TOKEN [ IGNORE_CASE ] :
{
  < EQUALS : "eq" >
| < NULL_TOKEN : "NULL" >
| < ATTR_TOKEN : ( ["a"-"z"] )+ >
}

void compileExpression() :
{}
{
  parseName()
  < EQUALS >
  (
    < NULL_TOKEN >
  | < DECIMAL_TOKEN > )
  < EOF >
}

void parseName() :
{}
{
  < ATTR_TOKEN >
  (
	< DOT > parseName()) ?
}
~~~

**Comment by kaikalur** [comment]
Which language?

**Comment by mbrigl** [comment]
I tested it on Java and C++, but I think C# has the same problem. The Java code is quite similar than the C# code. Debugging the generated tokenizer, you can see that if it find an exact token match like DOT in the example, it doesn't consider a token described by a regular expression like the DECIMAL_TOKEN, starting with a DOT as well

**Comment by kaikalur** [comment]
Let me check. That's unlikely. This is a standard "longest match first" thing. How about the interpreter? That should tell us if something in the core is broken

**Comment by mbrigl** [comment]
The Interpreter matches as well the DOT, instead of the DECIMAL

```
*** Starting in lexical state: DEFAULT
Token: ATTR_TOKEN; image: "NS" at: -1:1
Token: DOT; image: "." at: -1:6
Token: ATTR_TOKEN; image: "Attr" at: -1:8
Token: EQUALS; image: "eq" at: -1:15
Token: DOT; image: "." at: -1:18
Token: INTEGER_TOKEN; image: "56" at: -1:19
```

**Comment by kaikalur** [comment]
> The Interpreter matches as well the DOT, instead of the DECIMAL
> 
> ```
> *** Starting in lexical state: DEFAULT
> Token: ATTR_TOKEN; image: "NS" at: -1:1
> Token: DOT; image: "." at: -1:6
> Token: ATTR_TOKEN; image: "Attr" at: -1:8
> Token: EQUALS; image: "eq" at: -1:15
> Token: DOT; image: "." at: -1:18
> Token: INTEGER_TOKEN; image: "56" at: -1:19
> ```

:(

**Comment by kaikalur** [comment]
Also, note that it's not an issue with NFA. It's the optimization for strings literals (DFA) that's causing the issue.

**Comment by mbrigl** [comment]
> Also, note that it's not an issue with NFA. It's the optimization for strings literals (DFA) that's causing the issue.

Yes, you are right. It's the DFA, sorry.

**Comment by kaikalur** [comment]
I will look at some point but it should not be a blocker as you can always use `-no_dfa` option.
