### ISSUE TITLE
Install Steps Do Not Work

### ISSUE THREAD

**Issue by Black-Photon** [javacc/javacc#131]
Currently, the installation instructions specify that one should unzip the container, and add the bin folder to the path. However, the bin folder is now the scripts folder so the bin folder does not exist. The scripts inside search on paths that do not exist and the location the `javacc.jar` file should be placed is not specified. This makes it complex and difficult for a user to install and use javacc for the first time.

I suggest changing the classpath in `javacc.bat`, `jjdoc.bat` and `jjtree.bat` to `%~dp0../target/javacc.jar`. This will search for `javacc.jar` in `javacc/target` instead.

In addition, the fact that the jar must be added is not included in the install instructions. I suggest all build releases include `javacc.jar` in the `target` folder, or additional instructions such as:

> Finally, you should download or build `javacc.jar`, and place it in the target folder in the main directory.

Should be added to the `README.md` and website, with the references to `bin` replaced with `scripts`

**Comment by mantou16** [comment]
apparently this is an issue starting from v6.0 as someone claimed not find bin folder from v6.0. 
https://stackoverflow.com/questions/18674474/setting-javacc-to-work-with-command-prompt

Please modify the instruction on the javacc page. Thanks!
https://javacc.github.io/javacc/#download

**Comment by martinswanson** [comment]
If you’re on Mac OS you can just use the Homebrew formula
https://formulae.brew.sh/formula/javacc

If you’re on Windows <cough> then it’s worth reading the javacc.rb script
https://github.com/Homebrew/homebrew-core/blob/master/Formula/javacc.rb

**Comment by iwantleave** [comment]
yes, the install step is wrong. And now, no "bin" folder in the zip file. 
please use `java -cp bootstrap/javacc.jar javacc xxx.jj`.

**Comment by jvanhill** [comment]
Several issues as stated above:

- The javacc.jar is in the "bootstrap" folder, and not the "libs" folder as the scripts are pointing.
- The 'bin' directory appears to have been renamed to 'scripts'.

**Comment by Black-Photon** [comment]
>  * The javacc.jar is in the "bootstrap" folder, and not the "libs" folder as the scripts are pointing.

Just a note on that first point, the `javacc.jar` in `bootstrap/` is actually an old version of JavaCC being used to compile the new versions - the actual file is only generated on build, and is instead installed into `target/` (still not `libs` as documented)

**Comment by Black-Photon** [comment]
Fixed by #157
