### ISSUE TITLE
Use Gradle for the build

### ISSUE THREAD

**Issue by vlsi** [javacc/javacc#141]
Hi,

I see you have code movement in 8.0.0 branch, so I wonder what do you think of using Gradle as the build system?

It makes lots of things simpler to do (e.g. when compared with Ant and Maven), it and it improves development experience.

I've migrated Apache JMeter from Ant to Gradle, and Apache Calcite from Maven to Gradle.
In both cases, it resulted in significant improvements when it comes to day-to-day development. In both cases, Gradle made it simpler to release new versions.

**Comment by zosrothko** [comment]
You are welcome to contribute in this area of building JavaCC with Gradle.... and for testing the generated code (compiling/linking c++ and also c#)

Fox now, the full build with maven is under development and will be the next official way to produce/test JavaCC.

**Comment by martinswanson** [comment]
+1 for Gradle and I would be happy to help test it. Could run alongside Maven for a while? Would be nice to start with building and publishing the distributions as that’s quite manual and done infrequently.

**Comment by vlsi** [comment]
Building and publishing with Gradle is much simpler.

**Comment by martinswanson** [comment]
Yes, and the performance difference is significant, would help us move to a continuous build process, rather than long-lived branches.
https://gradle.org/gradle-vs-maven-performance/

**Comment by vlsi** [comment]
Just in case, here's the feedback from migration Apache JMeter from Ant to Gradle: https://lists.apache.org/thread.html/c08780952b7fbd71eccff717cb494562723e11dc99ea1b4bb39af461@%3Cdev.jmeter.apache.org%3E

**Comment by zosrothko** [comment]
I had already in the past tried to build JavaCC with gradle...without success...So, again, you are welcome to make it work. It is not so easy like 1,2,3!

**Comment by vlsi** [comment]
@zosrothko ,

can you please clarify?

https://github.com/javacc/javacc/tree/8.0.0

I see you are using git submodule for codegen.
Can we please refrain from that?
Can we just include codegen sources to javacc repository?

I happen to maintain [PostgreSQL official JDBC driver](https://github.com/pgjdbc/pgjdbc), and our experience shows that having a single repository greatly simplifies changes that span across repositories. For instance, if you have a PR to `codegen`, then it is extremely hard to provide a PR.

I see 8.0.0 tree duplicates examples folders: [here](https://github.com/javacc/javacc/tree/8.0.0/examples) and [here](https://github.com/javacc/javacc/tree/8.0.0/parser/examples)

What is the purpose of that duplication?

Can you please clarify which commit would you recommend to use for adding Gradle scripts?

**Comment by zosrothko** [comment]
IMO, you should exercise to build JavaCC with gradle on a branch derived from the master branch which is now at the 7.0.6 version. The 7.0 path is the stable mainstream code base for JavaCC. The 8.0.0 is currently a experimental WIP, with forthcoming organisation changes.

**Comment by vlsi** [comment]
OK. I see `master` has both `build.xml` and `pom.xml`.
Are they identical?
Which is primary?

**Comment by zosrothko** [comment]
ant was used first... now it is maven which is used

**Comment by vlsi** [comment]
Just in case: I see there's no much interest in Gradle build scripts at this point, so I no longer work on this issue / PR. Feel free to pick it up or close it.

**Comment by zosrothko** [comment]
As per the above discussion, javacc build is using Maven for now. May be later on, Gradle would be considered.
