### ISSUE TITLE
Discuss: javax.tools.JavaCompiler or Janino for grammar tests

### ISSUE THREAD

**Issue by vlsi** [javacc/javacc#145]
See https://github.com/javacc/javacc/pull/143#issuecomment-578058816

/cc @martinswanson 

A part of JavaCC testing complexity comes from the fact that it requires Java compiler to compile the generated grammar.

The current tests are written in Ant build files, which makes it complicated to debug, understand, maintain, etc, etc.

I suggest that most tests should be written like `unit` tests, so they can be executed from IDE.

I see the following possibilities:
A) `javax.tools.JavaCompiler` can be used since Java 1.6. That is the compiler can be accessed programatically. Then a test can first call JavaCC to generate the code, then `test framework` compiles it, then it executes it.

B) https://github.com/janino-compiler/janino can probably be used as well. They have https://janino-compiler.github.io/janino/apidocs/org/codehaus/janino/JavaSourceClassLoader.html which enables to use Java source files as if it were compiled bytecode.

C) Eclipse Compiler for Java (ECJ) is an option as well.

I'm inclined to `javax.tools.JavaCompiler`.
Any thoughts?

**Comment by martinswanson** [comment]
My vote is for the standard javax library. Please no dependencies on the Eclipse IDE ...!

**Comment by zosrothko** [comment]
I am also in favor of the javax library. @martinswanson The ECJ is independent of the Eclipse IDE and can be run as a standard Java application.

**Comment by zosrothko** [comment]
@vlsi Remind that Ant build will be removed at some point when the Maven one be stable...

**Comment by vlsi** [comment]
@zosrothko , Maven build is obsolete, so it should be removed even before all the build.xml files.

**Comment by vlsi** [comment]
https://github.com/javacc/javacc/pull/148 could be just enough.

**Comment by zosrothko** [comment]
@vlsi So you decide yourself that Maven build is obsolete!!! What a way to collaborate! I was alone on JavaCC during years, made most improvments in the build system (Ant & Maven) and you just come in and blow away what I have made... That 's not gona work like this!

**Comment by vlsi** [comment]
@zosrothko , I don't follow you.

Gradle scripts that I have added do more than both Ant and Maven combined.
It increases code coverage, and it improves the development experience.

I can see it might be surprising that it takes just a couple of days to get Gradle-based build fully working, however, it is indeed that simple.

If you do not want contributions, then just say that. I will close all the PRs, and that is it.

---

My initial intention was to implement https://github.com/javacc/javacc/issues/140 to increase coverage for JavaCC-generated parsers.

I tried to open JavaCC project in my IDE (which happens to be IntelliJ IDEA), and it was hard to do.

Now the code opens in IDE, I can run tests, I can debug parsers, I can navigate between .jj and generated Java files.

**Comment by vlsi** [comment]
Just in case, I closed this issue because I have actually implemented it, and it turned out it becomes hard to interact with the generated parser.

For instance, the parser class is not available to IDE (the file is compiled fully in memory), and it would take extra efforts to materialize the generated files. Then it would be hard to tell IDE to treat those files as source (e.g. for debugging).

Then, the generated parser has to be loaded via the new classloader. It means the only way to interact with the parser is to use Java Reflection API.
Do you like to use Java Reflection as the primary API in the tests?
I do not.

It turned out there's another approach: add an extra module that compiles the grammars before launching the tests.
Then the tests can reference the generated classes, and IDE can autocomplete method names, etc, etc.

The approach at https://github.com/javacc/javacc/pull/148 should be good for most of the cases.

`javax.tools.JavaCompiler`-based tests might indeed be helpful (e.g. for testing if JavaCC generates compilable classes), however, it is not in my priority for now.
