### ISSUE TITLE
Grammars : PHP.jj and PetalParser.jj are identical

### ISSUE THREAD

**Issue by mathieu-margier** [javacc/javacc#156]
I think there has been a wrong manipulation when committing the grammar of PHP : [grammars/PHP.jj](../blob/master/grammars/PHP.jj) and [grammars/PetalParser.jj](../blob/master/grammars/PetalParser.jj) are the same file, both containing PetalParser.

**Comment by zosrothko** [comment]
If you find out the PHP.jj grammar, I will replace it.

**Comment by mathieu-margier** [comment]
Here is the most recent one I can find :

**Comment by zosrothko** [comment]
Fixed
