### ISSUE TITLE
Consider binary compatibility for the generated code

### ISSUE THREAD

**Issue by vlsi** [javacc/javacc#159]
Current constants are generated as interface constants -> they are inlined by javac, so the client code must be recompiled every time the grammar is re-generated.

What if JavaCC produced constants in such a backward-compatible way?

For instance:
1) Generate `enum`
2) Use non-inlinable code for constants. For instance, if the constant is declared as `int DECIMAL_LITERAL = Math.max(42, 0)`, then javac does not inline it, and the users of `ParserConstancts.DECIMAL_LITERAL` would get up to date value for the token id even if they don't recompile.

See the following in the description of https://github.com/pmd/pmd/pull/2260 :

> since adding some token regexes breaks the binary API (token ids are inlined compile-time constants)

**Comment by oowekyala** [comment]
To note, that with option 2, it wouldn't be possible to switch on the token kind in the parser (switch requires constant expressions as labels).
A third solution, that uses ints as token kinds, would be to generate two files: 
* one for private use by the parser, where token ids are compile-time constants
* one for the public API, where the ids are not compile-time constants, and hence are not inlined in client code (eg declared with  `Math.max` like above, or initialized in a static block)

**Comment by vlsi** [comment]
Note: user code might want to have `switch(...)` over token kinds as well, so `enum` is probably ok.

**Comment by oowekyala** [comment]
@zosrothko What happened to this issue? Did you decide on something? and will #158 ever be merged?
