### ISSUE TITLE
Move discussion to a public place - like here

### ISSUE THREAD

**Issue by matozoid** [javacc/javacc#16]
Please don't force people to use Facebook.

**Comment by jeandersonbc** [comment]
There are some nice alternatives:
1. [Gitter](https://gitter.im/home)
2. [Slack](https://slack.com/)
3. Mailing list
4. IRC channel

Either option works fine and has been in use in many different open source communities.

**Comment by MarcMazas** [comment]
I agree "please do not force people to use Facebook".
And
Is there anybody tasked to manage the issues ? (validating pull requests, fixing bugs, ...) ?

**Comment by zosrothko** [comment]
@MarcMazas This is an open source projet and people that had a writer access to the old javacc.net project should have also the role of contributor here. If it not the case, please ask to kesav@viswanadha.net who is the administrator of this repo.

By the way, I just created a Slack team: javacc.slack.com: anybody can be a member, jsut give me your email address.

**Comment by zosrothko** [comment]
Discussion can happen on Slack team: `javacc.slack.com`. The Google group  `comp.compilers.tools.javacc` seems totally spammed. Any other tool?

**Comment by new-javacc** [comment]
??? That's the really old newgroup from more than 10 years ago. It's 
been long dead.

We now have the  google group:  groups.google.com and look for JavaCC.

**Comment by new-javacc** [comment]
Well, I just created that slack team :) So may be we can move the 
discussions to that channel.

**Comment by zosrothko** [comment]
"Well, I just created that slack team" Do not understand: the `javacc.slack.com` team was created on 2017/03/02... see above!

**Comment by new-javacc** [comment]
Hmm, that's weird. It did let me "create".

Anyway, it's good. I now see there are 4 people on there. Yeah sounds 
like a good platform for design discussions.
