### ISSUE TITLE
jjTree generates a method too large to compile

### ISSUE THREAD

**Issue by n-deutsch** [javacc/javacc#168]
In my project jjTree generates a method within FormulaParserTokenManager that's 5,972 lines long. This produces the following compilation error:
```
/Users/ndeutsch/(...)/table/formula/FormulaParserTokenManager.java:2303: error: code too large
private int jjMoveNfa_b_0(int startsAt, int i, int kind)
```
FormulaParserTokenManager.jjMoveNfa_b_0 is larger than 64kb of bytecode so it refuses to compile.

Currently running javacc-5.0. I tried running it with 7.0.0 but that created an even bigger method :(

**Comment by kaikalur** [comment]
You can try 8.0! 

In general though this usually means you have inefficiency in the grammar. I posted on this topic many times if you can find some old mailing list archives!

**Comment by kaikalur** [comment]
Actually, just look at the lexer tips document. I'm pretty sure you are doing one of the donts from that doc.

**Comment by zosrothko** [comment]
@kaikalur Sreeni, actually, there is no mailing list archived anywhere. Could you add the one saved from java.net.dev.javacc to the JavaCC github repository?

**Comment by n-deutsch** [comment]
Thanks guys, I'll take a look

**Comment by kaikalur** [comment]
OK Hopefully you found what's wrong with either your grammar or javacc :) If so, please post here for others info. Thanks!
