### ISSUE TITLE
Help with tutorial

### ISSUE THREAD

**Issue by rusnasonov** [javacc/javacc#171]
Hi, thanks for library!

I read [this](https://javacc.github.io/javacc/tutorials/examples.html#jjtree) tutorial and have some trouble with **jjtree**. `jjtThis.setName(t.image);` not working. I got error `error: cannot find symbol jjtn000.setName(t.image);` when compile `.jjt` file. How I can set name for node?

JavaCC 7.0.5

**Comment by zosrothko** [comment]
Please read this README: javacc-7.0\examples\JJTreeExamples\java\README

**Comment by rusnasonov** [comment]
Thanks, I understand — I need to change generated node class. But it's ok? JavaCC add checksum to end of file.

**Comment by zosrothko** [comment]
No, you need to copy the provided AST*.java class to the directory where is the grammar. JavaCC checks any file it should generate and does not override it if it exist

**Comment by rusnasonov** [comment]
Thanks!
