### ISSUE TITLE
Doesn't work in Turkish Locale

### ISSUE THREAD

**Issue by murkle** [javacc/javacc#175]
All calls to String.toLowerCase() / toUpperCase() should be changed to **String.toLowerCase(Locale.English_US)** / **toUpperCase(Locale.English_US)** so that they don't depend on the user's locale

See https://garygregory.wordpress.com/2015/11/03/java-lowercase-conversion-turkey/ for an explanation, in short "I".toLowerCase() doesn't give "i"

In particular options with "i" in don't work but there are likely other subtle bugs due to this

> Warning: Bad option "-static=false" will be ignored.
> Warning: Bad option "-unicode_input=true" will be ignored.

**Comment by zosrothko** [comment]
Which version of JavaCC are you using?

**Comment by murkle** [comment]
5.0, 6.1.2, 7.0.5

It's in current master eg https://github.com/javacc/javacc/blob/master/src/main/java/org/javacc/parser/JavaCCGlobals.java#L579

and it's good practice to replace (or at least review and comment) all uses of toLower/UpperCase()

**Comment by zosrothko** [comment]
Could you rename this javacc-7.0.8-SNAPSHOT.zip to javacc-7.0.8-SNAPSHOT.jar and test it?

[javacc-7.0.8-SNAPSHOT.zip](https://github.com/javacc/javacc/files/4745010/javacc-7.0.8-SNAPSHOT.zip)

**Comment by murkle** [comment]
Sorry, we can't check now. My colleague has re-installed Windows in English to workaround this

**Comment by murkle** [comment]
Thanks for the quick fix! 👍
