### ISSUE TITLE
Lookahead is broken since 7.0.5 (introduced in commit fbac68f)

### ISSUE THREAD

**Issue by dweiss** [javacc/javacc#183]
I tried to upgrade Apache Lucene query parser generators from an ancient javacc (5.0) to 7.0.9 and to my surprise they behaved differently - lookahead wasn't working as expected. I tracked down the change in behavior to 7.0.5 (7.0.4 is working correctly). 

Specifically, this commit: fbac68fbfb152c7dbb48f730d8e45a978941380c

I think this issue has been fixed by:
https://github.com/javacc/javacc/pull/73

but no up-to-date version of javacc has it?

**Comment by zosrothko** [comment]
The next release of javacc-7.0.10 will have the fix embedded. There is no release date as for now. Thus do you mind to use the javacc-7.0.4 version instead?

**Comment by dweiss** [comment]
I don't mind at all. But I spent a good hour looking for the problem... It should be stated clearly on javacc front page that versions 7.0.5 and on have a problem - would save people some time debugging!

**Comment by zosrothko** [comment]
Your are rigth @martinswanson Would you minde to update the documentation/README with the problem's statement with a large police?

**Comment by martinswanson** [comment]
Done. I just submitted a pull request for this.

**Comment by zosrothko** [comment]
Fixed in javacc-7.0.10
