### ISSUE TITLE
Typo on official documentation static web site 

### ISSUE THREAD

**Issue by shinux** [javacc/javacc#188]
Just noticed that a simple example on https://javacc.github.io/javacc/#example :
![image](https://user-images.githubusercontent.com/7784713/97149482-c3fc4800-17a7-11eb-8eae-9236b154ebac.png)

and for this simple example `}}}` is definitely an illegal input which may confuse rookie like me.

But I also noticed that  [origin doc file](https://github.com/javacc/javacc/blob/master/docs/tutorials/examples.md) is correct，guess something went wrong when  render page or generate static site.

**Comment by martinswanson** [comment]
It renders correctly when you view the document on GitHub
https://github.com/javacc/javacc/blob/master/README.md <https://github.com/javacc/javacc/blob/master/README.md>




I guess this is an issue with the way the GitHub pages theme renders the markup document ?

Martin
