### ISSUE TITLE
Grammar fix for AllocationExpression

### ISSUE THREAD

**Issue by MarcMazas** [javacc/javacc#189]
Hi
A small grammar fix:
change
void AllocationExpression() :
{}
{
  LOOKAHEAD(2)
  "new" PrimitiveType() ArrayDimsAndInits()
| "new" ClassOrInterfaceType() [ LOOKAHEAD(2) EmptyTypeArguments() | TypeArguments() ]
  (
    ArrayDimsAndInits()
  | Arguments() [ ClassOrInterfaceBody() ]
  )
}

and add
void EmptyTypeArguments() :
{}
{
  "<" ">"
}

**Comment by zosrothko** [comment]
@MarcMazas Could you provide a simple test that demonstrate your change proposal?
