### ISSUE TITLE
Fix doc for token_manager_decls

### ISSUE THREAD

**Issue by MarcMazas** [javacc/javacc#190]
In the doc (/docs/documentation/grammar.md), the token manager declarations java part is said to be a java_block, but it is rather a ClassOrInterfaceBody(). For example one can have 
TOKEN_MGR_DECLS : {
  static boolean isTM;
  static { isTM = false; }
}
which is more than a block.

**Comment by zosrothko** [comment]
@MarcMazas Hello Marc, could you provide a PR for your issue?

**Comment by MarcMazas** [comment]
Hi. I did the fix on my local repo, created a commit. But pushing it to javacc/javacc.git master replies with an error (git-receive-pack not permitted). I did create a personnal access token and used it for usr/pat login over https.
Do I have the appropriate rights (ie does I need to be a contributor)?

**Comment by zosrothko** [comment]
You need to do a PullRequest from your forked copy of javacc

**Comment by MarcMazas** [comment]
I git-cloned on my PC the javacc repo, created a commit and a branch on it.
I do not see how to create a PullRequest on the javacc repo referencing a branch on something other than another github repo.
Do I need to create a fork on github?
