### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by timbault** [javacc/javacc#194]
Hi,

are there any plans to support java 11 in the near future?

Thank you

Regards

**Comment by zosrothko** [comment]
What do you mean by "support Java 11"?

**Comment by timbault** [comment]
Hi,

"support java 11" means "compile javacc grammar with java11 and execute the generated code with java 11". 

![image](https://user-images.githubusercontent.com/25931001/113137723-31b01280-9225-11eb-8a46-8d0d2b0e9ab7.png)

**Comment by zosrothko** [comment]
Using Java 11, you can compile a Java 8 source code and execute it using the Java 11 JRE. While JavaCC itself is using features from the Java 1.7, it is compiled with the source & target JDK 1.8. Thus you can run the produced parser/lexer with Java 11 without any problem.

`Java 9 and Java 10 are not supported` means that the Java language features of those version are not handled by JavaCC, i.e., you cannot use Java 9 or Java 10 code in your actions.
