### ISSUE TITLE
Is the STRING_LITERAL lexer rule incomplete in the tutorial?

### ISSUE THREAD

**Issue by netcrystals** [javacc/javacc#197]
Hello,
I am currently writing a JavaCC Netbeans module. I used the official JavaCC grammar on your [homepage](https://javacc.github.io/javacc/documentation/bnf.html).
I think that the STRING_LITERAL

<STRING_LITERAL: "\"" (~["\"","\\","\n","\r"] | "\\" (["n","t","b","r","f","\\","\'","\""] | ["0"-"7"] (["0"-"7"])? | ["0"-"3"] ["0"-"7"] ["0"-"7"]))* "\"">

is incomplete. When my module highlights the tokens, unicode charaters "\uxxxx" are not identified correctly. I think, there is a 'u' missing in the token rule. I thinks it should be like this...

<STRING_LITERAL: "\"" (~["\"","\\","\n","\r"] | "\\" (["n","t","b","r","f",**"u"**,"\\","\'","\""] | ["0"-"7"] (["0"-"7"])? | ["0"-"3"] ["0"-"7"] ["0"-"7"]))* "\"">
Thanks.

**Comment by nineninesevenfour** [comment]
Hello @netcrystals ,
JavaCC uses the `JAVA_UNICODE_ESCAPE = true` option, so appearances of Uuicode escapes \u#### are preprocessed by `JavaCharStream` and therefore do not appear in the grammar.
