### ISSUE TITLE
Problem with README.md when displayed on home page

### ISSUE THREAD

**Issue by protasm** [javacc/javacc#225]
Hello, I'm not experienced with GitHub so I apologize for any mistakes.  I'm just dropping in to note that on the home page available at https://javacc.github.io/javacc/ there is a display problem with the section labeled 'Example'.  Specifically, the examples of legal and illegal strings are not displaying correctly.  I suspect it is because some of the braces are being interpreted by the web server as actual flow control symbols rather than simply as strings.

This section looks fine as README.md on the GitHub repository page, but it's getting a little garbled on the home page.  Thanks!

**Comment by martinswanson** [comment]
The README file is valid markdown code, and displays correctly in Safari, Chrome, and Firefox when viewed via the GitHub repository. The problem is specific to GitHub Pages, which is used to render the home page. Short of migrating off GitHub Pages, I am not aware of any fix we can practically do here.

**Comment by mroam** [comment]
As noted above, when browsing (Safari) to https://javacc.github.io/javacc/
The correct example    "{}", "{{{{{}}}}}", etc.           becomes       {}, }}} // … etc
And viewing the source html, I see the problem on line 179 which says
<p><code class="language-plaintext highlighter-rouge">{}</code>, <code class="language-plaintext highlighter-rouge">}}}</code> // … etc</p>

I guess that html is automatically generated from the README by  GitHub Pages? (I don’t see a separate gh-pages branch.)
A JavaCC rookie like me, on browser, might love a comment or link to the README.

**Comment by martinswanson** [comment]
As already mentioned this is an issue with GitHub Pages. The markdown is correct. 

GitHub Pages is rendered from /docs. 

There is already a link “View on GitHub”

**Comment by AlphaHinex** [comment]
Can we use zero-width space to fix this issue like https://github.com/javacc/javacc/pull/231 ?
