### ISSUE TITLE
Rename tag for "release" 6.1.3 

### ISSUE THREAD

**Issue by simonpoole** [javacc/javacc#226]
See this issue https://github.com/simonpoole/OpeningHoursParser/issues/72

tl;dr Debian unstable switched to 6.1.3 this month, this causes a compile fail in a not totally unimportant downstream project included in Debian. The root cause seems to be down to the naming of the relevant tag, this could be avoided by renaming it.

**Comment by zosrothko** [comment]
@simonpoole Do not understand what is the issue. Could you elaborate?

**Comment by simonpoole** [comment]
@zosrothko 6.1.3 is not backwards compatible with 6.1.2, or 5.x. All other 6.x or 7.x releases are. See the linked issue.

As a result of assuming that 6.1.3 is a bona fide release (because of numbering and naming) Debian is including a version of JavaCC that is clearly broken.

**Comment by zosrothko** [comment]
tag release-6.1.3 deleted.

**Comment by ebourg** [comment]
Btw, there is no tag for the 5.x releases, would it be possible to add at least the last one please?

**Comment by zosrothko** [comment]
Done as [release_5_9_3](https://github.com/javacc/javacc/releases/tag/untagged-49efe82912296f64b09d) but there is no source or binaries attached

**Comment by ebourg** [comment]
Thank you, does it match the javacc 5.0 artifact on [Maven Central](https://search.maven.org/artifact/net.java.dev.javacc/javacc/5.0/jar)? It was released on 2009-08-31, so the closest commit is 19e74b0900473ca2ae503fddd10b9c4bb5d8c104

**Comment by zosrothko** [comment]
it matches the branch version_593 on the git repository. Its README displays "JavaCC 5.0". So I suppose that is the one on [Maven Central](https://search.maven.org/artifact/net.java.dev.javacc/javacc/5.0/jar).

**Comment by ebourg** [comment]
The branch version_593 diverged from the HEAD branch on 2014-02-09 (bcfad9eeee6e880bbff2fb4caa444a8064ec9602), years after the upload of the version 5.0 to Maven Central. It looks more like a beta version of the 6.x line.

**Comment by zosrothko** [comment]
Release management in the past were quite a bit clumsy. For exemple, the commit you mention for javacc 5.0 ([19e74b0900473ca2ae503fddd10b9c4bb5d8c104] (https://github.com/javacc/javacc/commit/19e74b0900473ca2ae503fddd10b9c4bb5d8c104) on Maven Central is in fact the release 6.0 in the JavaCC github repo.

Fixed broken link

    [master](https://github.com/javacc/javacc) 

    [release_60](https://github.com/javacc/javacc/releases/tag/release_60) [release_7_0_2](https://github.com/javacc/javacc/releases/tag/release_7_0_2) [release_7_0_0](https://github.com/javacc/javacc/releases/tag/release_7_0_0) [release_6_1_2](https://github.com/javacc/javacc/releases/tag/release_6_1_2) [release_6_1_1](https://github.com/javacc/javacc/releases/tag/release_6_1_1) [release_6_1_0](https://github.com/javacc/javacc/releases/tag/release_6_1_0) [release_6_1_0_RC1](https://github.com/javacc/javacc/releases/tag/release_6_1_0_RC1) [release_6_0_1](https://github.com/javacc/javacc/releases/tag/release_6_0_1) [post_60_61_merge](https://github.com/javacc/javacc/releases/tag/post_60_61_merge) [javacc-7.0.11](https://github.com/javacc/javacc/releases/tag/javacc-7.0.11) [javacc-7.0.10](https://github.com/javacc/javacc/releases/tag/javacc-7.0.10) [javacc-7.0.9](https://github.com/javacc/javacc/releases/tag/javacc-7.0.9) [javacc-7.0.8](https://github.com/javacc/javacc/releases/tag/javacc-7.0.8) [javacc-7.0.7](https://github.com/javacc/javacc/releases/tag/javacc-7.0.7) [javacc-7.0.6](https://github.com/javacc/javacc/releases/tag/javacc-7.0.6) [7.0.5](https://github.com/javacc/javacc/releases/tag/7.0.5) [7.0.4](https://github.com/javacc/javacc/releases/tag/7.0.4) [7.0.3](https://github.com/javacc/javacc/releases/tag/7.0.3) [7.0.2](https://github.com/javacc/javacc/releases/tag/7.0.2) [7.0.1](https://github.com/javacc/javacc/releases/tag/7.0.1) 

tcopeland committed on 21 Jul 2009
1 parent [44589c7](https://github.com/javacc/javacc/commit/44589c7d4149346c18723aa3b05f2cbbb3e741a1) commit 19e74b0900473ca2ae503fddd10b9c4bb5d8c104

I have no idea how this Maven Central javacc 5.0 artifact was build. My contribution started whit the 7.0 version.

**Comment by ebourg** [comment]
The `release_60` tag points to the commit 26cc464899f7d5ddb8392f293a2f846178f07f8b which is from 2013 (unless someone changed it recently).

Tagging 19e74b0900473ca2ae503fddd10b9c4bb5d8c104 as `release_50` looks appropriate.
