### ISSUE TITLE
Production works with the Gradle Plugin, but fails with the Maven Plugin

### ISSUE THREAD

**Issue by manticore-projects** [javacc/javacc#229]
Greetings.

Very strange observation: The following Production would compile with the Gradle Plugin, but fail with the Maven Plugin:
```javacc
Test myTest(): 
{
   Test result;
}
{
    (
      result=TestProduction1() { return result; }
    )
    |
    (
      result=TestProduction2() 
    ) { return result; }
}
```

Error from the Maven build:
```
Error:  /home/runner/work/JSqlParser/JSqlParser/target/generated-sources/javacc/net/sf/jsqlparser/parser/CCJSqlParser.java:[3337,9] unreachable statement
Error:  /home/runner/work/JSqlParser/JSqlParser/target/generated-sources/javacc/net/sf/jsqlparser/parser/CCJSqlParser.java:[3345,1] missing return statement
```

Rewriting it solves the problem:
```javacc
Test myTest(): 
{
   Test result;
}
{
    (
        (
          result=TestProduction1() { return result; }
        )
        |
        (
          result=TestProduction2() 
        )
    ) { return result; }
}
```

For details, please refer to: https://github.com/JSQLParser/JSqlParser/pull/1552#issuecomment-1145917623

**Comment by blutorange** [comment]
I'm not that familiar with Gradle, but as far as I can see, the Gradle plugin still uses version 6 of JavaCC (https://github.com/javacc/javaccPlugin/blob/59cd9f786030e08d16afb298ccb850e149d30f70/subprojects/plugin/build.gradle#L35) whereas the Maven plugin already uses version 7. That might explain the different behavior.

**Comment by new-javacc** [comment]
Please try version 8.0 as we would like to move everyone over to that version. Also the code generator is split out of the main core so you can fix it yourself rather easily now and also improve it if you are interested.

**Comment by blutorange** [comment]
Oh interesting, I didn't even know about that version 8 project. Perhaps you could consider adding the maven/gradle plugin to the multi module project directly, like [they're doing it with the antlr plugin](https://github.com/antlr/antlr4/blob/master/antlr4-maven-plugin/pom.xml#L8-L12), which might help to keep the plugin up-to-date with the javacc version?

**Comment by manticore-projects** [comment]
Closed, since adding the extra brackets seems to work-around well.
