### ISSUE TITLE
Bibtex citation?

### ISSUE THREAD

**Issue by AngledLuffa** [javacc/javacc#249]
Do you have a system paper or other resource for citing this project?  We made extensive use of it in Stanford CoreNLP.  We hope to publish a paper regarding a previously unpublished component of CoreNLP, and citing JavaCC would be appropriate.

**Comment by new-javacc** [comment]
No :( We never published anything on it

**Comment by AngledLuffa** [comment]
We'll include a link as a footnote, then!

Thanks for the very useful piece of software.
