### ISSUE TITLE
It seems that JJDoc does not handle spaces in file paths properly.

### ISSUE THREAD

**Issue by wanderson-rigo** [javacc/javacc#261]
Hello. I installed the JavaCC plugin on Eclipse 2023. However, when I try to generate documentation for a .jj file using the menu, the HTML file is not generated. I suspect that the reason is because the path to the .jj file contains a whitespace, which is not being handled properly. I was able to generate the HTML file by creating a .bat file with the following content:

java -classpath C:\Users\Wanderson\.p2\pool\plugins\sf.eclipse.javacc_1.5.33\jars\javacc-6.0.jar jjdoc -OUTPUT_FILE=C:\Users\Wanderson\Downloads\ParserBNF.html "D:\IFC\Google Drive\MyProject\src\lookahead\Lookahead.jj"

Note that the paths are enclosed in quotation marks to handle the space in "Google Drive".

On the other hand, the JavaCC console in Eclipse says:

java  -classpath C:\Users\Wanderson\.p2\pool\plugins\sf.eclipse.javacc_1.5.33\jars\javacc-6.0.jar jjdoc -OUTPUT_FILE=C:\Users\Wanderson\Downloads\ParserBNF.html D:/IFC/Google Drive/aulas/Compiladores/eclipse/JavaCC/src/lookahead/Lookahead.jj

**Comment by MarcMazas** [comment]
Hi. You should post this bug report to the JavaCC Eclipse Plugin site (https://sourceforge.net/projects/eclipse-javacc/), not the JavaCC site.

**Comment by MarcMazas** [comment]
Hi. Could you close this issue ?
