### ISSUE TITLE
Modern template creates non-compiling code

### ISSUE THREAD

**Issue by phax** [javacc/javacc#28]
Affects JavaCC 6.1.3 and 7.0.2

The line ` throw new RuntimeException("Missing return statement in function");` is not generated when the modern template is active (see `Options.isLegacyExceptionHandling()`)

The source of the error is https://github.com/javacc/javacc/blob/master/src/main/java/org/javacc/parser/ParseEngine.java#L709-L712
The "if" in line 709 must be removed, because currently the code line is only generated, when the legacy exception handling is enabled (so this block is never entered if the modern template is used!)

Edit: here is a compiler output when using JavaCC 7.0.2 with ph-css and the modern template:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default
-compile) on project ph-css: Compilation failure: Compilation failure:
[ERROR] /P:/git/ph-css/ph-css/target/generated-sources/javacc/com/helger/css/parser/ParserCSS30.java
:[586,1] missing return statement
[ERROR] /P:/git/ph-css/ph-css/target/generated-sources/javacc/com/helger/css/parser/ParserCSS30.java
:[3469,1] missing return statement
[ERROR] -> [Help 1]
```

**Comment by wumpz** [comment]
When is this going to be solved? I want to use modern style, but in connection with jjtree it is not useable.

**Comment by phax** [comment]
The pull request got merged, so it should be in the next release....

**Comment by wumpz** [comment]
So when is the next release planned? :)

**Comment by zosrothko** [comment]
I will make a new release soon: should be 7.0.3... But anyone that would like to publish it are welcome too

**Comment by new-javacc** [comment]
I have a couple of fixes I want to merge before we release. I will get them in today.Also, @tobias you can just get the latest code and simply do 'ant' in the root to build a new javacc.jar if you are blocked on this issue.On Oct 23, 2017 5:56 AM, zosrothko <notifications@github.com> wrote:I will make a new release soon: should be 7.0.3... But anyone that would like to publish it are welcome too

**Comment by new-javacc** [comment]
Ok I merged my changes. We can probably cut build 7.0.3 now.On Oct 23, 2017 6:41 AM, JavaCC Support <support@javacc.org> wrote:I have a couple of fixes I want to merge before we release. I will get them in today.Also, @tobias you can just get the latest code and simply do 'ant' in the root to build a new javacc.jar if you are blocked on this issue.On Oct 23, 2017 5:56 AM, zosrothko <notifications@github.com> wrote:I will make a new release soon: should be 7.0.3... But anyone that would like to publish it are welcome too

**Comment by wumpz** [comment]
Why is this still open? Merge and release 7.0.3 as lready done.
