### ISSUE TITLE
How to process unicode char with ‍Zero Width Joiner

### ISSUE THREAD

**Issue by Xinlong-Wu** [javacc/javacc#283]
Hi all,

I got a problem when using javacc to scan unicode.

I'm using code 
```
options {
  DEBUG_PARSER = false;
  DEBUG_LOOKAHEAD = false;
  DEBUG_TOKEN_MANAGER = false;
  UNICODE_INPUT = true;
  STATIC = false;
  JDK_VERSION = "1.9";
}

...

TOKEN:
{
//<UNICODE : "'" (~["'"])+ "'">
<UNICODE : "'" ["\u0000"-"\uffff"] (["\u0000"-"\uffff"] (["\u0000"-"\uffff"])? )? "'" >
//'➿'   (\u27bf)
//'🧒'   (\ud83e\udd92)
//'🧒️'  (\ud83e\udd92\u200d)
}
```

The point is definition of token `UNICODE`.

first, I need scan the unicode `'➿'`, so I have defined it as  `<UNICODE : "'" ["\u0000"-"\uffff"] "'" >.` it works.

Then, I am trying let it can also process `'🧒'`, so I have defined it as `<UNICODE : "'" ["\u0000"-"\uffff"] (["\u0000"-"\uffff"] )? "'" >`. it also works.

finally, I want it also consider the case of unicode with Zero Width Joiner, in same logic, defined it as  `<UNICODE : "'" ["\u0000"-"\uffff"] (["\u0000"-"\uffff"] (["\u0000"-"\uffff"])? )? "'" >`, it does work for '🧒'   (\ud83e\udd92) and '🧒️'  (\ud83e\udd92\u200d). But when I trying to type '➿', it will waiting for another input forever.

Can anyone points what is the problem? How should I fix it?

**Comment by MarcMazas** [comment]
Hi. Please post your support questions at https://groups.google.com/g/javacc-users, if they are not javacc issues.
The token definition is not the problem (it works with Parser p = new Parser(new StringReader("yourinput"));): you may have a problem in the input reader you use.
By the way JDK_VERSION = "1.9"; does not do what you expect and is useless. See the manual.
