### ISSUE TITLE
C# End of line 

### ISSUE THREAD

**Issue by skfcz** [javacc/javacc#287]
Hello All, 

I generated a C# parser and get a problem with the <EOF>.

The exception is 

System.IndexOutOfRangeException : Der Index war außerhalb des Arraybereichs.
   bei prostep.aveva.vol.SimpleCharStream.getBeginLine() in C:\home\cz\OPS\opdm-aveva-val-parser\aveva-vol-csharp\src\CharStream.cs:Zeile 238.
   bei prostep.aveva.vol.VOLParserTokenManager.getNextToken() in C:\home\cz\OPS\opdm-aveva-val-parser\aveva-vol-csharp\src\VOLParserTokenManager.cs:Zeile 394.
   bei prostep.aveva.vol.VOLParser.jj_scan_token(Int32 kind) in C:\home\cz\OPS\opdm-aveva-val-parser\aveva-vol-csharp\src\VOLParser.cs:Zeile 1517.
   ....

and the generated code

 for (;;) {
    // First see if we have any input at all.
    try {
      curChar = input_stream.BeginToken();
    } catch(System.Exception) {
    if (lexStateNames.Length > 1) {
      System.Console.Error.Write("<" + lexStateNames[curLexState] + "> ");
    }
    System.Console.Error.WriteLine("Reached EOF at " +
                       input_stream.getBeginLine() + ":" +
                       input_stream.getBeginColumn());

the input_stream reached EOF, and the system.console causes the indexofofrange exception.

**Comment by MarcMazas** [comment]
Hi. This javacc (7) (in this repo) does not support C# code generation. See repos javacc 8 / javacc-8-core / javacc-8-csharp and submit your issues there.

**Comment by skfcz** [comment]
Sorry, I copy this to the right repo.
