### ISSUE TITLE
Homepage says that javacc 7.0.14 is the current version, but no such version exists

### ISSUE THREAD

**Issue by jmillikin** [javacc/javacc#291]
![Screenshot_2024-09-05_14-26-27](https://github.com/user-attachments/assets/ce78fc10-a516-4928-a7b4-84dc7e4bbdc8)

It looks like the most recent commit to the homepage (in February) changed that section (https://github.com/javacc/javacc/commit/58b24f27c51505168fd1cc6a06e64e1237c8068f#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6L168-R165), but all the links 404 since there is no 7.0.14 release in Github or Maven.

**Comment by MarcMazas** [comment]
Fixed.
