### ISSUE TITLE
JavaCC 7.0.12, Java 21, try-with-resources block causes error

### ISSUE THREAD

**Issue by DeadComposer** [javacc/javacc#293]
I have the following try-with-resources block in the Java code section of my .jj file:

try (InputStream is = new FileInputStream(fileName)) {
}

JavaCC errors out when it sees the '(' in front of the try statement, and says it's expecting a '{'.

I'm using Java 21, so try-with-resources should be recognized.

**Comment by MarcMazas** [comment]
The javacc parser embeds a java 1.7 syntax and a partial java 1.8 syntax, no more. One day we'll catch up the latest java versions...
Try to put your java code (e.g. your main(...) and other glue) outside the .jj file.

**Comment by DeadComposer** [comment]
That's odd, because the JavaCC plugin version 7.0.12 for Eclipse 2024-03 doesn't have the same reaction to the try-with-resources block, but processes it just fine when I run JavaCC from within Eclipse.

**Comment by MarcMazas** [comment]
Well, this is really odd. I believe the story is that the JavaCC Eclipse plugin maintainer (me, when I was not also the javacc maintainer) silently fixed a few things (for my personal use) in the (embeded) javacc jar he shipped with the plugin and kept it with the same name / version.
