### ISSUE TITLE
C++ codegen seems broken

### ISSUE THREAD

**Issue by new-javacc** [javacc/javacc#35]
Whoever is messing with C++ code generator - please doublecheck it with:

examples/JavaGrammar/cpp
just run make clean; make and make sure it compiles and also try and test the generated parser.

For example, right now, I get 100s of errors in the main branch. Looks like jjtree C++ code gen is hosed, Can whoever thinks broke it take a look? I will try and find the CR that broke it later tonight,

/* Generated By:JJTree: Do not edit this line. Node.h Version 7.0 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_E
XTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef JAVACC_NODE_H
#define JAVACC_NODE_H

#include <vector>
#include "JavaCC.h"
#include "Token.h"

namespace java {
namespace parser {

/* All AST nodes must implement this interface.  It provides basic
   machinery for constructing the parent and child relationships
   between nodes. */

class JavaParser
class Node {
  friend class SimpleNode;

**Comment by zosrothko** [comment]
I am the faulty guy.. Fixing asap...


Le 03/11/2017 à 00:42, JavaCC Support a écrit :

**Comment by zosrothko** [comment]
Fixes pushed in master
cpp/javaparser.exe Test.java >Test.txt
[Test.txt](https://github.com/javacc/javacc/files/1440342/Test.txt)

**Comment by zosrothko** [comment]
Fixed in 7.0.3
