### ISSUE TITLE
Consider setting up continuos integration with Travis CI

### ISSUE THREAD

**Issue by ftomassetti** [javacc/javacc#43]
In this way tests would be running for every Pull Request

**Comment by ftomassetti** [comment]
To do this we need two thingsL

1. Someone who is a member of the repository needs to register on travis-ci.org and enable Travis integration for this repository
2. We need to create a build script for Travis

I can do number 2 if someone does number 1 first. @zosrothko can you look into this?

**Comment by inponomarev** [comment]
👍 more than a year passed, but the project still certainly needs the CI

@zosrothko all you need is just enable Travis build for the project. If @ftomassetti is not available now, I can help with number 2.

**Comment by zosrothko** [comment]
@new-javacc Could you grant me access to the javacc project for Travis CI.
`Access request pending @javacc `

**Comment by inponomarev** [comment]
Hi @new-javacc, I see a recent activity in the project. What do you think about this CI idea?

**Comment by zosrothko** [comment]
@inponomarev That's a very good idea but I am not able to setup the Travis script. try to make it happen...
