### ISSUE TITLE
escaping generates faulty code

### ISSUE THREAD

**Issue by eduarddrenth** [javacc/javacc#48]
Dear all,

I have this:

`|   <VALUE: ( ~[",",")","|"] )* ~["\\",",",")","|"] >`

which results in this:

```
private int jjMoveStringLiteralDfa0_2(){
   switch(curChar)
   {
      case ')':
         return jjStopAtPos(0, 7);
      case ',':
         return jjStopAtPos(0, 9);
      case '\':
         return jjMoveStringLiteralDfa1_2(0x1000L);
      case '|':
         return jjStopAtPos(0, 11);
      default :
         return jjMoveNfa_2(2, 0);
   }
}

```

Am I doing something wrong? This works with maven plugin 2.6 / javacc 5 and 6.

perhaps this issue is for ph-javacc-maven-plugin 4.0.3.

Bye

**Comment by new-javacc** [comment]
Which version of JavaCC are you using? Do you have a test case?

The code is optimized by merging some arrays etc.so you can't really 
tell from the code. Did you  try DEBUG_TOKEN_MANAGER option?

**Comment by eduarddrenth** [comment]
the issue is with using ph-javacc-maven-plugin 4.0.3. Don't know which version of javacc that uses.

tried commandline javacc 7.0.3, that does not generate faulty code, same function as  above now looks like:

```
private int jjMoveStringLiteralDfa0_2(){
   switch(curChar)
   {
      case 41:
         return jjStopAtPos(0, 7);
      case 44:
         return jjStopAtPos(0, 9);
      case 92:
         return jjMoveStringLiteralDfa1_2(0x1000L);
      case 124:
         return jjStopAtPos(0, 11);
      default :
         return jjMoveNfa_2(2, 0);
   }
}

so, I'll move this issue to the maven plugin
```
