### ISSUE TITLE
javacc.org is out of date

### ISSUE THREAD

**Issue by HoldYourWaffle** [javacc/javacc#77]
The [javacc.org](https://javacc.org/download) site still promotes javacc 6.
While searching for why this would be the case, I found out that there's a javacc 8 in development. Is this stable for use?

**Comment by zosrothko** [comment]
You could use the latest stable version javacc-7.0.4 available on [Maven Repository](https://mvnrepository.com/)

**Comment by costabas** [comment]
Yes, please update the site. I thought the product is dead until I found the git repository.

**Comment by martinswanson** [comment]
Is anyone working on updating the docs / site? I would be happy to look at this.

**Comment by albert-github** [comment]
The problem is still present (I submitted a new issue).

**Comment by zosrothko** [comment]
@HoldYourWaffle The JavaCC version 8 is a WIP solution that splits the JavaCC parser from the code generators (actually, targets are Java, C++ & C#). This is an unstable development that would be inappropriate for production. Keeping the JavaCC 7.0.5 is a better choice until JavaCC 8 be alpha released or better.

**Comment by albert-github** [comment]
I agree that on javacc.org version 7.05 should be mentioned (as requested too in #122) and not the (very) old version 6. O the download page a reference to github could be added as well (as now it is only (?) the main page).
In the readme on github it is possible to mention the version 8 as being WIP.

**Comment by zosrothko** [comment]
@albert-github Done in the master branch.
