### ISSUE TITLE
Is there a possibility to switch off tokens via options?

### ISSUE THREAD

**Issue by wumpz** [javacc/javacc#90]
I have the need to build a parser for two different language versions. I want to avoid to build two parsers and have two grammar files. Using semantic Lookahead one is able to switch production on/off. The same would be nice for tokens.

I tried token modes, but in reality, I have multiple options/flags that could be combined. Therefore this is not a valid way.

As mentioned I would like to skip to build a parser for each of my options combinations.

**Comment by wumpz** [comment]
Or maybe there is the possibility to change tokens via options. For example, I have in mind to have a token for string literals. I want two methods to insert a quote, one by doubling the quote and one by a backslash:

'abc''abc'
'abc\'abc'

Is it possible to build a token that would depend on a token manager option only one of these types accept?

**Comment by new-javacc** [comment]
I'm not sure I understand the issue here. You can have both tokens in the same grammar and use lexical action to accept/reject it. If you can explain clearly what you are trying to do, I can give you better ideasOn May 5, 2019 11:39 PM, Tobias <notifications@github.com> wrote:Or maybe there is the possibility to change tokens via options. For example, I have in mind to have a token for string literals. I want two methods to insert a quote, one by doubling the quote and one by a backslash:
'abc''abc'
'abc'abc'
Is it possible to build a token that would depend on a token manager option only one of these types accept?

**Comment by wumpz** [comment]
I read the documentation about lexical actions. The problem here is, that this action is executed after the TokenManager has processed a token, to modify the returned one. I want the TokenManager not even recognize the "skipped" token, but process another valid one.

This issue / question resulted from https://github.com/JSQLParser/JSqlParser/issues/677. 

There is a token accepting all "quoted" literals. Some databases support bracket quotation like

`select [abc]`

But some databases using brackets to address an item within an array.

`select arr [abc]`

The array index can be a complete expression. Therefore a token is not valid.

**Comment by phax** [comment]
My 50 cents: `token_source.SwitchTo (DEFAULT);` lets you choose an initial lexical state, where `xxxTokenManager` is your `token_source`. So if you don't use lexical states currently, this might help here...
See https://javacc.org/tutorials/tokenmanager for lexical state help.

**Comment by wumpz** [comment]
@phax I don't think those states will help. My explanation was for one situation. In fact there are multiple that could be combined in many ways. Or do I understand a state wrong?

**Comment by phax** [comment]
@wumpz My understanding was, that you want one grammar, but based on the underlying DB system, you want slightly different lexical parsing rules. When manually calling `SwitchTo` **before** parsing, you can set these states. But of course it bloats the grammar - see https://github.com/phax/ph-css/blob/master/ph-css/src/main/jjtree/ParserCSS30.jjt#L77 and following for an example how I use different lexing states. It might not be the nicest solution, but it might help....

**Comment by matozoid** [comment]
JavaParser does this by having the widest, most encompassing grammar possible, then marking invalid constructs for a specific language level with an AST visitor. There is also one rule that may rewrite parts of the AST.

(This can of course get very complex. Java has been so nice to stay backwards compatible, so every new version's grammar is a superset of the previous one.)

**Comment by wumpz** [comment]
Looking at all this it seems to me, JavaCC should be improved to handle these situations better, to give the grammar designer a better toolset, to get a less complex grammar.

How hard is it to provide this possibility (switching on/off tokens) within the token manager? Or is there a better idea to tackle those multi variant grammars?

I want to avoid at any cost to maintain multiple variants of one grammar.

**Comment by new-javacc** [comment]
If you want it at parser build time, you can simply use one of the existing tools like m4 or something to preprocesss and generate specific grammars from a general grammar. Another way is to have one common file and anything that's specific in a separate file and concatenate appropriate fragments at build time. If you want a single parser accepting different languages, that gets more complicated and probably not worth the complexity.

**Comment by hackmann** [comment]
We sometimes use a longer token than want we really want to match because it is too short. And then split it in the lexer. Here is an example where `ALPHA1_RBD_DATE` does not just match a RBD but also a date and then `AlphaRBD` splits it into an RBD token and a DATE token.

```
TOKEN :
{
  < NUM1 : [ "0" - "9" ] >
| < ALPHA1 : [ "A" - "Z" ] >
| < ALPHA2 : < ALPHA1 > < ALPHA1 > >
| < ALPHA3 : < ALPHA2 > < ALPHA1 > >
| < NUM2 : < NUM1 > < NUM1 > >
| < DAYMONTH : < NUM2 > < ALPHA3 > >
| < DAYMONTHYEAR : < DAYMONTH > < NUM2 > >
| < ALPHA1_RBD_DATE : < ALPHA1 > ( < DAYMONTHYEAR > | < DAYMONTH > ) >
}

// Trick JavaCC into parsing a ALPHA1_RBD_DATE token into two nodes (AlphaRBD and Date)
void AlphaRBD() :
{}
{
  < ALPHA1 >
  {
    jjtThis.append(token);
  }
| < ALPHA1_RBD_DATE >
  {
    jjtThis.append(token, 0, 1);
    String image = token.image.substring(1);
    int type = image.length() == 5 ? AvsGrammarConstants.DAYMONTH : AvsGrammarConstants.DAYMONTHYEAR;
    Token date = Token.newToken(type, image);
    date.next = token.next;
    token.next = date;
  }
}
```

I think you can use such an approach for `S_QUOTED_IDENTIFIER` and then add ` "[" Expression() "]"`

**Comment by new-javacc** [comment]
IMO that's a non-requirement. Doing it at runtime is ugly and a maintenance nightmare. If you are processing one language at a time, you should just have build rules to produce different parsers. If not preprocessor, use the other idea of maintaining separate grammar fragments.Anyway you can do that at runtime too. You can't just "turn off" rules. But you can do that simply using code. Remember that javacc matches longest one first. So for all ambiguous things, just add an action in the longest rule to check if you want that or not and you split it manually. For your example of quoting with [], in the rule for quoted I'd check the flag and if you don't want tyta match, then simply adjust the token kind/image to LSQUARE, put back all chars except the first one and continue normal processing.Another option would be to have a token manager subclass and override the GetNextToken method to do this so grammar looks clean.Finally, the new code generators is now modular so feel free to extend it to turn off tokens programmatically. Look at the latest head and JavaCCInterpreter class for ideas.

**Comment by wumpz** [comment]
@new-javacc I was not aware, that I could put back characters within a lexical action. That is the kind of thing I needed. However, I think about how I would like that defined in JavaCC. Sure, there could be some Java code, but wouldn't it be cool if I could write something like:

TOKEN {
  <LSQUARE : "[" >
  | TOKEN_LOOKAHEAD( !dontUseThis, LSQUARE )  <QUOTED: "[" ... "]">
}

Like using a sematic Lookahead and JavaCC would take care of putting back all characters and deliver LSQUARE in case of dontUseThis is true.

**Comment by new-javacc** [comment]
In javacc, unlike Antlr, we compile the token spec down to bit vectors so this will be an expensive check to add. You can use lexical actions to do tOn May 8, 2019 12:35 PM, Tobias <notifications@github.com> wrote:@new-javacc I was not aware, that I could put back characters within a lexical action. That is the kind of thing I needed. However, I think about how I would like that defined in JavaCC. Sure, there could be some Java code, but wouldn't it be cool if I could write something like:
TOKEN {
<LSQUARE : "[" >
| TOKEN_LOOKAHEAD( !dontUseThis, LSQUARE )  <QUOTED: "[" ... "]">
}
Like using a sematic Lookahead and JavaCC would take care of putting back all characters and deliver LSQUARE in case of dontUseThis is true.

**Comment by wumpz** [comment]
@new-javacc I know that. But that is one of the reasons JavaCC generated parsers have such superior performance (https://dzone.com/articles/antlr-and-javacc-parser-generators). My idea was, that JavaCC could behind the scenes build this lexical action for me :).

**Comment by wumpz** [comment]
I tried to follow the described way to replace the matched token, but somehow I am not able to put back the characters into my stream. My code looks like that:

```
int length = matchedToken.image.length();
matchedToken.kind = ...Constants.ST_LBRACKET;
matchedToken.image = "[";
input_stream.backup(length -1);
```

I thought using backup, I put those remaining characters back into the stream.

**Comment by new-javacc** [comment]
That should work provided you don't have other issues with lexical 
states etc

**Comment by wumpz** [comment]
@new-javacc Then the problem is on an other place. Hmm.

**Comment by wumpz** [comment]
It was my fault. Now it works as expected. I was using a customized SimpleCharStream, that was not able to handle token actions.

**Comment by wumpz** [comment]
If I want to support backslash and double quote escaping within string literals, should I go the same way?

**Comment by MarcMazas** [comment]
> 
> 
> JavaParser does this by having the widest, most encompassing grammar possible, then marking invalid constructs for a specific language level with an AST visitor. There is also one rule that may rewrite parts of the AST.
> 
> (This can of course get very complex. Java has been so nice to stay backwards compatible, so every new version's grammar is a superset of the previous one.)

Hi. So you are using semantic checks (and in JJT, not JavaCC) to solve a syntactic need?

**Comment by zosrothko** [comment]
@wumpz May be you could do this token disambiguity by using `TOKEN_MGR_DECLS `and `CommonTokenAction `in which you can check and remind for a first "[", then check and remind for the 'abc', then check and remind the closing ']'. In case of a single token '[acd]', then replace the token '[' by a new token '[abc]', link it to the previous token of '[' and remove the 'abc' and ']' tokens. For sure, the rules should be change to accomodate this hack. I did not try it but that's an idea

**Comment by matozoid** [comment]
Oh, @MarcMazas, yes, in a way, not sure if it should be called "semantic" then. And an update: more recent Java versions have been more wild with changes, and now some tricks have been used to make token types configurable, and to accept some tokens as identifiers too. I just wrote a bit about it on the JavaParser gitter channel.
